### ISSUE TITLE
Current version cannot compile in Android Studio. 

### ISSUE THREAD

**Issue by Delaley** [cmusphinx/pocketsphinx-android-demo#10]
Ive tried for days now. It still cannot compile. Any work around.
Am getting gradle build error.

**Comment by nshmyrev** [comment]
Please provide the build error.

**Comment by Delaley** [comment]
Error:(1, 0) Plugin with id
'com.android.application' not found.
I've tried all solutions suggested by Android communities and blogs. Android works with all projects but never compiled CmuSphinx.

**Comment by nshmyrev** [comment]
This question is covered here:

http://stackoverflow.com/questions/24795079/error1-0-plugin-with-id-com-android-application-not-found

you need to update your gradle and Android build tools

**Comment by Delaley** [comment]
Believe me I've already done that.
I've gone ahead and downloaded and tested all gradle versions from 1.0 to 2.8.None worked for CmuSphinx.
I want to use this in Unity 3d is it doable.

**Comment by Delaley** [comment]
If its Possible can I get a complete Android Studio Project to download.

**Comment by nshmyrev** [comment]
Android studio project is available here on github, you just clone the project.
