### ISSUE TITLE
Support for simple ARPA LM files?

### ISSUE THREAD

**Issue by efung** [cmusphinx/pocketsphinx-android-demo#11]
I was trying to create my own simple language model using the Web-based lmtool [service](http://www.speech.cs.cmu.edu/tools/lmtool-new.html). I upload a file containing two sentences (<20 unique words)

After the model is generated, I downloaded the `.tgz` file, copied the `1234.lm` file into `app/src/main/assets/sync` and also added an entry in `assets.lst`. I register it using:

        File languageModel = new File(assetsDir, "1234.lm");
        recognizer.addNgramSearch(CUSTOM_SEARCH, languageModel);

From the logs, I can see that my language model file is recognized on startup.

However, I never get any result in `onPartialResult` nor in `onResult`. 

Should I be able to use the `.lm` files generated by the web service?

**Comment by nshmyrev** [comment]
Your lm is uppercase, our default dictionary is lowercase. You need to change the dictionary to make case match or convert lm to lowercase.

Then it will work.
