### ISSUE TITLE
App crashes immediately launched on Android.

### ISSUE THREAD

**Issue by Delaley** [cmusphinx/pocketsphinx-android-demo#15]
I managed to figure extremely complex thing and after installation I opened the app and it crashes.

**Comment by nshmyrev** [comment]
You need to provide logcat output

**Comment by Delaley** [comment]
The reason why some of us Use third party libraries is really because we
cannot know all things so when it comes conditions such as this we easily
get discouraged from further attempt.After gruesomelly spending ours trying
to make this thing work I finally did it and it crashed.
