### ISSUE TITLE
Noise cancellation

### ISSUE THREAD

**Issue by adonislapin** [cmusphinx/pocketsphinx-android-demo#31]
The FAQ said "In sphinxbase/pocketsphinx/sphinxtrain it's 'remove_noise' option." How can Activate it?, Can I activate it from Android code or I should recompile pocketsphinx full library?

**Comment by nshmyrev** [comment]
It is activated by default.

To deactivate you can use `config.set_boolean("-remove_noise", false)` in java source code.

**Comment by adonislapin** [comment]
Thank you very much
