### ISSUE TITLE
Pocketsphinx blocks the mic during phonecall

### ISSUE THREAD

**Issue by Ponpoorani** [cmusphinx/pocketsphinx-android-demo#33]
As long as the pocketsphinx app is running(even in the background), I am not able to listen to the voice during any phonecall. The pocketsphinx blocks the mic for some reason. Please look into this.

**Comment by nshmyrev** [comment]
Pocketsphinx demo is just a demo, it is not supposed to be full-featured application and handle all corner cases. You can stop recording microphone in a phone call yourself.
