### ISSUE TITLE
Too many false positive

### ISSUE THREAD

**Issue by jaumard** [cmusphinx/pocketsphinx-android-demo#34]
Hi,
I test on both Android mobile and watch (1.5 not 2.0 yet) and it works :) but too many false positive for hot key detection :( is there any way to improve that ? configuration or something maybe I miss

Here is what I use: 

```
public static final String KEYPHRASE = "hey lisa";
public static final String KWS_SEARCH = "wakeup";
....
recognizer = SpeechRecognizerSetup.defaultSetup()
                .setAcousticModel(new File(assetsDir, "en-us-ptm"))
                .setDictionary(new File(assetsDir, "cmudict-en-us.dict"))
                .getRecognizer();
        recognizer.addListener(this);
        // Create keyword-activation search.
        recognizer.addKeyphraseSearch(KWS_SEARCH, KEYPHRASE);
        recognizer.startListening(KWS_SEARCH);
```

Thanks for your work !

**Comment by nshmyrev** [comment]
There is a threshold you can tune.

**Comment by jaumard** [comment]
Thanks @nshmyrev, I miss that method, but can't find an explanation of what I have to put as value :/ on the tutorial it's something like `.setKeywordThreshold(1e-20f)` but there no explanation of what that value represents or do.

**Comment by nshmyrev** [comment]
http://cmusphinx.sourceforge.net/wiki/tutoriallm#keyword_lists
