### ISSUE TITLE
Phonetic Recognition does not work on atleast oneplus x and 3t

### ISSUE THREAD

**Issue by gwario** [cmusphinx/pocketsphinx-android-demo#35]
Hi,
the phonetic recognition does not seem to work on oneplus 3t and oneplus x.
The logcat output in https://gist.github.com/gwario/22441691717c683710c2538e222edef9 shows what's happening on the 3t when i start the demo app, navigate to the phonetic recognition and say 'this is a test' but all i get is 'SIL T P EH S Z AE TH SIL'.

oneplus 3t runs oxygenos 4.1.3/ android 7.1.1

Would be great if you could take a look at it...
If you need any further information, let me know.

regards.

**Comment by nshmyrev** [comment]
Not clear what do you mean by "does not work". It outputs the result 'SIL T P EH S Z AE TH SIL'. It is not supposed to be 100% accurate.

**Comment by gwario** [comment]
I wasn't expecting 100% accuracy, but i tested several words and sentences, and i was not able to get anything recognized correctly. the output is always a combination of one to 3 letters as in the example above.

**Comment by nshmyrev** [comment]
To get help on the accuracy you need to provide the audio data. It is stored on the device sdcard as logcat says.

**Comment by gwario** [comment]
I did another test. The audio data and the logcat is in [pocketsphinx-android-demo-data.zip](https://github.com/cmusphinx/pocketsphinx-android-demo/files/964064/pocketsphinx-android-demo-data.zip)

**Comment by nshmyrev** [comment]
Well, phonetic accuracy is not great by itself and the device has very bad microphone quality it seems. You can not do much about it.

**Comment by gwario** [comment]
Okay, thank you for looking into it.
