### ISSUE TITLE
Why Call runRecognizerSetup Twice?

### ISSUE THREAD

**Issue by lxc-xx** [cmusphinx/pocketsphinx-android-demo#37]
I noticed in PocketSphinxActivity.java, the function runRecognizerSetup() is called on both onCreate() and onRequestPermissionsResult(). If I understand the code correctly, the onRequestPermissionsResult() will be called when the permission request result gets returned by the system. To me, it seems the recognizer is initialized twice.

**Comment by nshmyrev** [comment]
Sorry, I do not see the problem you are describing. When we call recognizer setup in `onRequestPermissions` we do not call it in `onCreate`, see the `return` statement in permission check branch. 

Please provide the logcat if you still think recognizer is initialized twice.
