### ISSUE TITLE
assets.xml not find

### ISSUE THREAD

**Issue by NaeemMughal** [cmusphinx/pocketsphinx-android-demo#38]
anybody can help when i am compiling pocketsphinx-android-demo i am facing assets.xml not find 
my eyes are waiting for your reply ...........
![android demo](https://user-images.githubusercontent.com/24993270/27514343-903e029c-593c-11e7-8a14-6148cbdb77f3.png)

**Comment by nshmyrev** [comment]
You are using outdated demo it seems, clone a new one from github.

**Comment by NaeemMughal** [comment]
thank you i have done
