### ISSUE TITLE
Phonetic search demo issue

### ISSUE THREAD

**Issue by devdeep1987** [cmusphinx/pocketsphinx-android-demo#40]
I am trying the phonetic search demo but it does not seem to recognize words. The keyphrase, digits and weather demos seem to work reasonably. To start the phonetic search demo, I say "phones" in the menu and then I say something simple like "hello world" but it outputs text such as "SIL T EH  Y OW". Is there something I am doing wrong or is the model not setup properly or is this feature still in the works?

**Comment by nshmyrev** [comment]
You can share raw files and logcat output to get help on this issue.

**Comment by devdeep1987** [comment]
I am unable to attach the raw files but I have attached the log since the time i said "phones"
[log.txt](https://github.com/cmusphinx/pocketsphinx-android-demo/files/1123302/log.txt)

**Comment by nshmyrev** [comment]
You can share raw file on Google Drive and give here a link.

**Comment by devdeep1987** [comment]
I have shared the files here:
https://drive.google.com/open?id=0B9dqUt7kF6fRTkhqYm5tRVRjSHM
