### ISSUE TITLE
Not precise dets noise as voice

### ISSUE THREAD

**Issue by RayDragon** [cmusphinx/pocketsphinx-android-demo#43]
I recently tried to make home automation, pocket-sphinx was used to trigger the google speech-text api.
I actually used word Jarvis to trigger the action, however it gets triggered even on noise. Is there any way to remove it.

**Comment by nshmyrev** [comment]
Tune threshold as described in documentation https://cmusphinx.github.io/wiki/tutoriallm/#keyword-lists
