### ISSUE TITLE
Compile fails on recent default install of Android Studio

### ISSUE THREAD

**Issue by stprior** [cmusphinx/pocketsphinx-android-demo#44]
When importing a project from version control as described in https://cmusphinx.github.io/wiki/tutorialandroid/#building-and-running-from-android-studio I am prompted to select a gradle folder. This not described in the instructions so I select the gradle version installed with Android Studio (version 4.1)

After downloading some packages the build fails with error
error:Unable to find method 'org.gradle.api.artifacts.ProjectDependency.getProjectConfiguration()Lorg/gradle/api/artifacts/Configuration

I believe this is due to incompatibility between the android sdk/tools specified in app/build.gradle and the version of gradle. Using Gradle 3.5 allows the install to proceed succesfully

**Comment by nshmyrev** [comment]
Thank you, I fixed it in 60ee71693524928571cc47e8b01eabd8b94e6e04
