### ISSUE TITLE
I need just hotword detection 

### ISSUE THREAD

**Issue by viju2008** [cmusphinx/pocketsphinx-android-demo#46]
Dear Sir,

I need just hotword detection and want to use SPHINX . I  want to ensure that the app size increase due to addition of pocket sphinx should not be more than 5 MB. Is this possible.

I have reduced the 3 MB dict to 2 KB.  The Major chunk is being used by the  	en-us-ptm folder . How can i reduce the size of the en-us-ptm folder. As i may not require such a huge acoustic model.

Please guide me

**Comment by viju2008** [comment]
I saw that mdef and sendump and variances are binary files which are taking maximum size. How can i reduce the size

**Comment by nshmyrev** [comment]
You can train your own model
