### ISSUE TITLE
Unable to build in Android Studio

### ISSUE THREAD

**Issue by chrisspen** [cmusphinx/pocketsphinx-android-demo#60]
I tried following [these instructions](https://cmusphinx.github.io/wiki/tutorialandroid/#pocketsphinx-android-demo), but they no longer worker work in the current version of Android Studio 4.1.1 on Ubuntu.

After selecting  the option to start a new project from source control, using https://github.com/cmusphinx/pocketsphinx-android-demo as the URL, it seemed to create the project successfully. However, the "Build" panel shows the error:

    Failed to find target with hash string 'android-26' in: /home/chris/Android/Sdk

Presumably, this means it's missing the required Android version. However, your instructions said:

    "Once the project is set up, your IDE will update and download all dependencies automatically."

Searching for this error message shows this type of error is [somewhat common](https://stackoverflow.com/questions/33417537/failed-to-find-target-with-hash-string-android-23). However, none of the suggested solutions work for me. I've just installed Android Studio, so I have no cache to clear. And the solution to install the dependency via the SDK Manager doesn't work because there's no reference to an SDK Manager anywhere in Android Studio.

Do you still support Android Studio, or has this been deprecated? How else can I build the demo on Linux?

**Comment by nshmyrev** [comment]
You need to figure out which sdk do you have installed. SDK manager is there in the Tools. For more update you can check:

https://developer.android.com/studio/intro/update

To open the SDK Manager from Android Studio, click Tools > SDK Manager or click SDK Manager  in the toolbar. If you're not using Android Studio, you can download tools using the sdkmanager command-line tool.

Probably you have android-29 instead of 26.

**Comment by chrisspen** [comment]
That's strange. I read an article saying the SDK Manager should be under Tools, but nothing called that was in my default Tools menu. Then I ran some recommended plugin updates, and now it's showing up.

**Comment by chrisspen** [comment]
It seems to have built now. However, there are two options to "run" the project. Should I run "app" or "wear"?

**Comment by nshmyrev** [comment]
wear is for Watches and similar devices

**Comment by chrisspen** [comment]
Running neither app nor wear seems to have any effect.

Running `gradle installDebug` from the command line fails with the error:

    com.android.builder.testing.api.DeviceException: No connected devices!

Even though I have an Android 10 device connected via USB.

**Comment by chrisspen** [comment]
Nevermind. I had enabled USB debugging, but because I enabled that while my phone as already connect, I apparently needed to disconnect and reconnect my phone for my computer to recognize it.

**Comment by chrisspen** [comment]
I was able to successfully install it via `gradle installDebug` and then run it from the application menu.

The only oddity is it appears to install two seemingly duplication applications, which use different icons.
