### ISSUE TITLE
Failed to init recognizer 

### ISSUE THREAD

**Issue by ataafarin** [cmusphinx/pocketsphinx-android-demo#7]
Hi,
I compiled the sample project on android studio and tested it on Samsung Galaxy S4, I got this error : 
`failed to init recognizer,Java.io.FileNotFoundException:sync/assets.lst`

**Comment by ataafarin** [comment]
I saw that some body have this problem exist when they did not include below code in their build.gradle:
`ant.importBuild 'assets.xml'
 preBuild.dependsOn(list, checksum)
 clean.dependsOn(clean_assets)`
but the sample project that i downloaded from here already has it.

**Comment by nshmyrev** [comment]
You need to provide full logcat output to get help on this issue

**Comment by ataafarin** [comment]
I tested with other devices and got same error,here is logcat for `edu.cmu.pocketsphinx.demo` on galaxy s4 in debugging mode:
Thanks in Advance

`
10-14 09:57:57.336    9160-9160/edu.cmu.pocketsphinx.demo D/ResourcesManager﹕ creating new AssetManager and set to /data/app/edu.cmu.pocketsphinx.demo-1/base.apk
10-14 09:57:57.461    9160-9160/edu.cmu.pocketsphinx.demo V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/sym_def_app_icon.png
10-14 09:57:57.476    9160-9160/edu.cmu.pocketsphinx.demo V/BitmapFactory﹕ DecodeImagePath(decodeResourceStream3) : res/drawable-hdpi-v4/icon.png
10-14 09:57:57.481    9160-9160/edu.cmu.pocketsphinx.demo D/Activity﹕ performCreate Call secproduct feature valuefalse
10-14 09:57:57.481    9160-9160/edu.cmu.pocketsphinx.demo D/Activity﹕ performCreate Call debug elastic valuetrue
10-14 09:57:57.506    9160-9194/edu.cmu.pocketsphinx.demo D/OpenGLRenderer﹕ Render dirty regions requested: true
10-14 09:57:57.521    9160-9160/edu.cmu.pocketsphinx.demo D/Atlas﹕ Validating map...
10-14 09:57:57.586    9160-9194/edu.cmu.pocketsphinx.demo I/OpenGLRenderer﹕ Initialized EGL, version 1.4
10-14 09:57:57.586    9160-9194/edu.cmu.pocketsphinx.demo W/OpenGLRenderer﹕ Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
10-14 09:57:57.596    9160-9194/edu.cmu.pocketsphinx.demo D/OpenGLRenderer﹕ Get maximum texture size. GL_MAX_TEXTURE_SIZE is 4096
10-14 09:57:57.596    9160-9194/edu.cmu.pocketsphinx.demo D/OpenGLRenderer﹕ Enabling debug mode 0
10-14 09:57:57.606    9160-9194/edu.cmu.pocketsphinx.demo E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
10-14 09:57:57.611    9160-9194/edu.cmu.pocketsphinx.demo E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
10-14 09:57:57.616    9160-9194/edu.cmu.pocketsphinx.demo E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
10-14 09:57:57.616    9160-9194/edu.cmu.pocketsphinx.demo E/﹕ [android_ws] Format: 5, Width: 1080, Height: 1920
10-14 09:57:57.951    9160-9160/edu.cmu.pocketsphinx.demo I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@3b176814 time:53981281
10-14 09:58:07.506    9160-9160/edu.cmu.pocketsphinx.demo I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@3b176814 time:53990835
`

**Comment by nshmyrev** [comment]
According to the log you never sync assets. You need to review your code and demo code in order to see where you miss the important call.

**Comment by ataafarin** [comment]
I just run your sample project and the sync code you mentioned exist in `PocketSphinxActivity.java` : 
```
       new AsyncTask<Void, Void, Exception>() {
            @Override
            protected Exception doInBackground(Void... params) {
                try {
                    Assets assets = new Assets(PocketSphinxActivity.this);
                    File assetDir = assets.syncAssets();
                    setupRecognizer(assetDir);
                } catch (IOException e) {
                    return e;
                }
                return null;
            }
```

**Comment by nshmyrev** [comment]
Looking on your apk file I see that assets.lst was not created. Most likely reason is that you are using some unusual android studio or there were build errors.

Provide full gradle build log after clean.

Provide the version of Android Studio you are using.

**Comment by ataafarin** [comment]
My android studio version is 1.1.0 , built on feb 18, 2015.
  `Provide full gradle build log after clean`
when i open the project in android  studio,it always shows a message to migrate project to gradle.because it is not in gradle system.should i migrate?here is the screenshot:

![sphinxproblem](https://cloud.githubusercontent.com/assets/2671352/10562623/85a22228-7572-11e5-9219-b58d0b1cef24.png)

**Comment by nshmyrev** [comment]
Migrate, sure. How did you build it then without migration.

Maybe you can just update Android Studio. I have version 1.2.1.1, everything works out of box.
